from test_common import CommonTests, SignedRequestTests
from test_management_commands import SyncFacebookTestUsersTests, FixTestUserFixtureTests
from test_urls import UrlTests, FacebookUrlTests
from test_middleware import FacebookRedirectMiddlewareTests, FandjangoMiddlewareTests
from test_test_module import TestFacebookTestCase1, TestFacebookTestCase2, TestFacebookTestCase3, TestFandjangoIntegration, GetAppNameTestCase