from test_common import CommonTests, SignedRequestTests
from test_management_commands import SyncFacebookTestUsersTests, FixTestUserFixtureTests, FandjangoIntegrationTest
from test_urls import UrlTests, UrlTestsNoCanvasRemoval, FacebookUrlTests
from test_middleware import FandjangoMiddlewareTests
from test_test_module import TestFacebookTestCaseFixture1, TestFacebookTestCaseFixture2, TestFacebookTestCaseFixture3, TestClient, GetAppNameTestCase, TestFacebookUsersSync